name = "short-urls"
main = "src/index.ts"
compatibility_date = "2023-09-04"
account_id = "502aea548379e08369697540cc0bb0d1"
workers_dev = false
routes = [{ pattern = "pydis.com", custom_domain = true }]
kv_namespaces = [{ binding = "urls", id = "c6d38750203b40e89579731430d22429" }]
