name: Deploy Workers

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Workers
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for all sub-workers
        run: find . -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' -exec sh -c 'cd {} && npm install' \;

      - name: Run lint task for all workers
        run: xargs -n1 -r0a <(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' -print0) sh -c 'for file do cd $file && npm run deploy && cd ..; done;' sh
        env:
            CLOUDFLARE_ACCOUNT_ID: 502aea548379e08369697540cc0bb0d1
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
