name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build-deploy:
    uses: ./.github/workflows/deploy.yml
    needs:
      - lint
    secrets: inherit
